### ISSUE TITLE
Не происходит загрузка медитаций на IOS

### ISSUE THREAD

**Issue by Eugene-elt** [evolution-corporation/dmd-meditation#20]

**Comment by Eugene-elt** [comment]
![Снимок экрана 2023-01-13 161141](https://user-images.githubusercontent.com/72036195/212307010-cceb0ece-6329-40c3-bad8-ebff8ac14475.png)
![image](https://user-images.githubusercontent.com/72036195/212307234-44fc680b-25a0-49ce-8eb2-aae41e1449c8.png)

какие то медитации загружаются какие то нет, происходит на чистом рандоме, в основном все не загружаются

**Comment by Eugene-elt** [comment]
![image](https://user-images.githubusercontent.com/72036195/212308748-93e21b76-b9b2-444e-a410-6b3abb4fa3d0.png)
Момент когда медитации не загружается

**Comment by HardKot** [comment]
@Eugene-elt по данным графикам можно лишь судить о том что происходит отдача, а затем скорость падает, но не прерывается, соединение не теряется
